<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\ErtisAuth.Dto\ErtisAuth.Dto.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Ertis.Data" Version="10.0.0" />
    </ItemGroup>
</Project>