<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" Version="5.0.0" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Ertis.Core" Version="10.0.2" />
        <PackageReference Include="Ertis.Net" Version="10.0.1" />
        <PackageReference Include="MailKit" Version="4.17.0" />
        <PackageReference Include="SendGrid" Version="9.29.3" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
    </ItemGroup>
</Project>