version: '3.1'

services:
    mongo:
        container_name: ertisauth_mongo
        image: mongo
        restart: always
        volumes:
            - ${HOME}/.docker/volumes/ertisauth:/data/db
        ports:
            - "27017:27017"
    web_api:
        container_name: ertisauth_web_api
        image: ertugrulozcan/ertisauth:latest
        ports:
            - "9716:80"
        environment:
            - Database__Host=ertisauth_mongo
        depends_on:
            - mongo
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        links:
            - mongo