<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
		<PackageId>ErtisAuth.Sdk</PackageId>
		<PackageVersion>10.0.0</PackageVersion>
		<Version>10.0.0</Version>
		<Authors>Ertuğrul Özcan</Authors>
		<Description>ErtisAuth SDK</Description>
		<PackageTags>authentication;authorization;identity;iam;openid-connect;oauth</PackageTags>
		<Copyright>© 2026 Ertuğrul Özcan</Copyright>
		<PackageProjectUrl>https://github.com/ertugrulozcan/ErtisAuth</PackageProjectUrl>
		<RepositoryUrl>https://github.com/ertugrulozcan/ErtisAuth</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
    <ItemGroup>
		<ProjectReference Include="..\ErtisAuth.Core\ErtisAuth.Core.csproj" />
    </ItemGroup>
    <ItemGroup>
		<PackageReference Include="Ertis.Net" Version="10.0.7" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.12" />
    </ItemGroup>
</Project>