using Ertis.Core.Models;
using ErtisAuth.Abstractions.Services;
using ErtisAuth.Core.Exceptions;
using ErtisAuth.Core.Models.Identity;
using ErtisAuth.Core.Models.Roles;
using ErtisAuth.Extensions.Authorization.Attributes;
using ErtisAuth.Extensions.AspNetCore.Extensions;
using ErtisAuth.Extensions.AspNetCore.Services;
using ErtisAuth.Extensions.AspNetCore.Attributes;
using ErtisAuth.WebAPI.Models.TokenCodes;
using Microsoft.AspNetCore.Mvc;

namespace ErtisAuth.WebAPI.Controllers;

[ApiController]
[Tags("Token Codes")]
[Authorized]
[RbacResource("tokens")]
[MembershipRoute("codes")]
public class TokenCodesController : ControllerBase
{
	#region Services
	
	private readonly ITokenCodeService _tokenCodeService;
	private readonly IUtilizerService _utilizerService;
	
	#endregion
	
	#region Constructors
	
	/// <summary>
	/// Constructor
	/// </summary>
	/// <param name="tokenCodeService"></param>
	/// <param name="utilizerService"></param>
	public TokenCodesController(ITokenCodeService tokenCodeService, IUtilizerService utilizerService)
	{
		this._tokenCodeService = tokenCodeService;
		this._utilizerService = utilizerService;
	}
	
	#endregion
	
	#region Methods
	
	/// <summary>Generate a token code</summary>
	/// <remarks>Starts the code flow for devices without a keyboard: returns a short <c>user_code</c> (generated by the membership's code policy) to show on the device, and a <c>device_code</c> which only the device keeps, to get the token with. The device's <c>X-IpAddress</c> and <c>X-UserAgent</c> headers (or the request's own values) are shown to the user before the approval. **Note:** the <c>device_code</c> is returned only in this response.</remarks>
	/// <param name="membershipId">Membership id</param>
	/// <param name="cancellationToken">Cancellation token</param>
	[HttpPost]
	[RbacAction(Rbac.CrudActions.Create)]
	[ProducesResponseType<TokenCodeWithDeviceCode>(StatusCodes.Status201Created)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status401Unauthorized)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status403Forbidden)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status404NotFound)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status503ServiceUnavailable)]
	public async Task<IActionResult> GenerateCode([FromRoute] string membershipId, CancellationToken cancellationToken = default)
	{
		var tokenCode = await this._tokenCodeService.CreateAsync(membershipId, this.GetClientInfo(), cancellationToken: cancellationToken);
		return this.Created($"{this.Request.Scheme}://{this.Request.Host}{this.Request.Path}/{tokenCode.UserCode}", tokenCode);
	}
	
	/// <summary>Get a token code</summary>
	/// <remarks>Returns the code with the given user code and the device that requested it (<c>client_info</c>), to show to the user before the approval. Needs a Bearer token. Case, dashes and spaces in the user code are ignored.</remarks>
	/// <param name="membershipId">Membership id</param>
	/// <param name="userCode">User code shown on the device</param>
	/// <param name="cancellationToken">Cancellation token</param>
	[HttpGet("{userCode}")]
	[RbacAction(Rbac.CrudActions.Create)]
	[ProducesResponseType<TokenCode>(StatusCodes.Status200OK)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status400BadRequest)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status401Unauthorized)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status403Forbidden)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status404NotFound)]
	public async Task<IActionResult> GetCode([FromRoute] string membershipId, [FromRoute] string userCode, CancellationToken cancellationToken = default)
	{
		this.EnsureBearerToken();
		return this.Ok(await this._tokenCodeService.GetByUserCodeAsync(userCode, membershipId, cancellationToken: cancellationToken));
	}
	
	/// <summary>Approve a token code</summary>
	/// <remarks>Approves the code for the user of the Bearer token: the device gets a token of that user with its device code. A code can be approved or denied only once.</remarks>
	/// <param name="membershipId">Membership id</param>
	/// <param name="userCode">User code shown on the device</param>
	/// <param name="cancellationToken">Cancellation token</param>
	[HttpPost("{userCode}/approve")]
	[RbacAction(Rbac.CrudActions.Create)]
	[ProducesResponseType<TokenCode>(StatusCodes.Status200OK)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status400BadRequest)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status401Unauthorized)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status403Forbidden)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status404NotFound)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status409Conflict)]
	public async Task<IActionResult> ApproveCode([FromRoute] string membershipId, [FromRoute] string userCode, CancellationToken cancellationToken = default)
	{
		this.EnsureBearerToken();
		var utilizer = await this._utilizerService.GetUtilizerAsync(this.User, cancellationToken: cancellationToken);
		return this.Ok(await this._tokenCodeService.ApproveAsync(userCode, membershipId, utilizer, cancellationToken: cancellationToken));
	}
	
	/// <summary>Deny a token code</summary>
	/// <remarks>Denies the code, e.g. when the user doesn't recognize the device: the device's token requests answer <c>TokenCodeDenied</c>. A code can be approved or denied only once.</remarks>
	/// <param name="membershipId">Membership id</param>
	/// <param name="userCode">User code shown on the device</param>
	/// <param name="cancellationToken">Cancellation token</param>
	[HttpPost("{userCode}/deny")]
	[RbacAction(Rbac.CrudActions.Create)]
	[ProducesResponseType<TokenCode>(StatusCodes.Status200OK)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status400BadRequest)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status401Unauthorized)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status403Forbidden)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status404NotFound)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status409Conflict)]
	public async Task<IActionResult> DenyCode([FromRoute] string membershipId, [FromRoute] string userCode, CancellationToken cancellationToken = default)
	{
		this.EnsureBearerToken();
		var utilizer = await this._utilizerService.GetUtilizerAsync(this.User, cancellationToken: cancellationToken);
		return this.Ok(await this._tokenCodeService.DenyAsync(userCode, membershipId, utilizer, cancellationToken: cancellationToken));
	}
	
	/// <summary>Get a token with a device code</summary>
	/// <remarks>Anonymous: the device polls with its <c>device_code</c> until the code is approved, at most once per <c>interval</c> seconds. Returns a token of the approving user, once. Answers <c>UnauthorizedTokenCode</c> while the code is not approved yet, <c>TokenCodeSlowDown</c> when polled too often, <c>TokenCodeDenied</c> or <c>TokenCodeExpired</c> when the device must request a new code.</remarks>
	/// <param name="membershipId">Membership id</param>
	/// <param name="model">The device code</param>
	/// <param name="cancellationToken">Cancellation token</param>
	[Unauthorized]
	[HttpPost("token")]
	[ProducesResponseType<BearerToken>(StatusCodes.Status201Created)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status400BadRequest)]
	[ProducesResponseType<ErrorModel>(StatusCodes.Status401Unauthorized)]
	public async Task<IActionResult> GenerateToken([FromRoute] string membershipId, [FromBody] TokenCodeTokenFormModel model, CancellationToken cancellationToken = default)
	{
		var token = await this._tokenCodeService.GenerateTokenAsync(model.DeviceCode ?? string.Empty, membershipId, cancellationToken: cancellationToken);
		return this.Created($"{this.Request.Scheme}://{this.Request.Host}", token);
	}
	
	/// <summary>
	/// The device is signed in as the user of the token, so only a user's Bearer token can decide on a code.
	/// </summary>
	[NonAction]
	private void EnsureBearerToken()
	{
		var token = this.GetToken();
		if (token.TokenType != SupportedTokenTypes.Bearer)
		{
			throw ErtisAuthException.UnsupportedTokenType();
		}
	}
	
	[NonAction]
	private ClientInfo GetClientInfo()
	{
		var ipAddress = this.Request.Headers.TryGetValue("X-IpAddress", out var ipAddressHeader) ? ipAddressHeader.ToString() : null;
		var userAgent = this.Request.Headers.TryGetValue("X-UserAgent", out var userAgentHeader) ? userAgentHeader.ToString() : null;
		
		return new ClientInfo
		{
			IPAddress = string.IsNullOrEmpty(ipAddress) ? this.HttpContext.Connection.RemoteIpAddress?.ToString() : ipAddress,
			UserAgent = string.IsNullOrEmpty(userAgent) ? this.Request.Headers.UserAgent.ToString() : userAgent
		};
	}
	
	#endregion
}
