<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\ErtisAuth.Extensions.Mailkit\ErtisAuth.Extensions.Mailkit.csproj" />
        <ProjectReference Include="..\ErtisAuth.Integrations.OAuth.Core\ErtisAuth.Integrations.OAuth.Core.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Ertis.Core" Version="10.0.2" />
        <PackageReference Include="Ertis.Schema" Version="10.0.0" />
    </ItemGroup>
</Project>